### PR TITLE
:fire: implement hotfix for main branch

### PR DESCRIPTION
**Pull request by nils-schmitt**
This PR fixes a fatal error, that came along with the last PR. I am sorry for any inconveniences.

### CODE REVIEW

**Comment by tkv29** [comment]
Looks good, but I'm not sure if we should push the migration. Did you change anything at the PatientJourney model?

**Comment by nils-schmitt** [comment]
This File was created by default, i'm fine with not pushing it

**Comment by nils-schmitt** [comment]
Nevermind, the file is needed because of my changings in the logic (specificly in the usage of patient_journey and patien_journey_sentences)

**Review by PitButtchereit — APPROVED** [review]
I did not really get what the problem was. Can you explain quickly?

**Comment by nils-schmitt** [comment]
In the previous merge there was the bug, that the preprocessor needed an dataframe or any input, as requirement. As no dataframe exists when the preprocessor is called, that needs to be defaulted to none, which wasn't the case. That's why this fix was needed.

**Pull request merged**
