### PR TITLE
Feature/basic main journeys

### LINKED ISSUE #9: First patient journeys
As a developer, I want to gather several patient journeys from different sources, so that we can test our program.

**Description:** The user stories should be gathered from different sources so that we have more variety. That includes synthetical, generated and publicly available data. It should cover different diseases.

**Estimated Size:** 1 week

# Definition of Ready
- [x] the user story still has room for discussion
- [x] the user story must have value for the stakeholders
- [x] the user story can be implemented in one sprint
- [x] the user story has been drafted by at least 3 people

# Acceptance Criteria
- [x] 10 patient journeys all saved in different txt files 
- [x] several resources should be used e.g. mamahealth, self-drafted, web
- [x] different diseases are described
- [x] all patient journeys should include timestamps and activities
- [x] the files are saved in the repository 

# Definition of Done
- [x] all acceptance criteria are fulfilled
- [ ] the files have been reviewed by 2 other people

### PR DESCRIPTION
**Pull request by soeren227**
Added 20 patient journeys as .txt-files. 
10 synthetic journeys and 10 real world experience journeys with different patient cohorts and a high level of information density.

This pull request closes #9

### CODE REVIEW

**Comment by nils-schmitt** [comment]
looks good to me, could be merged

**Comment by FR-SON** [comment]
looks very good, all acceptance criteria have been met. One idea we should discuss: Do we want to sort journeys by disease? For example, put all journeys belonging to a disease in one folder? I am in favour of at least naming them accordingly (`journey_rw_covid_1`). Then it is easier to select a specific one when importing.

**Review by FR-SON — COMMENTED** [review]
looks very good, all acceptance criteria have been met. One idea we should discuss: Do we want to sort journeys by disease? For example, put all journeys belonging to a disease in one folder? I am in favour of at least naming them accordingly (`journey_rw_covid_1`). Then it is easier to select a specific one when importing.

**Review by nils-schmitt — APPROVED** [review]

**Review by thangixd — APPROVED** [review]
Everything looks good.

**Review by thangixd — APPROVED** [review]

**Pull request merged**
