### PR TITLE
Feature/39 refactoring static UI

### PR DESCRIPTION
**Pull request by soeren227**
#39 
Add static directory structure supported by django and move general styling from html files to style.css file. 
Now supports static files like e.g images being loaded into html files.

### CODE REVIEW

**Review by PitButtchereit — APPROVED** [review]
Joop

**Review by nils-schmitt — CHANGES_REQUESTED** [review]
LGTM, but the IS_TEST should be turned off before merging

**Comment by PitButtchereit** [comment]
@thangixd @soeren227 is this still on?

**Review by thangixd — APPROVED** [review]
u are right. I changed it to false

**Pull request merged**
