### PR TITLE
Bugfix/95 exception handling

### PR DESCRIPTION
**Pull request by PitButtchereit**
I've created an `error_page.html` that displays the error traceback and lets you return to the landing page. This process clears all artifacts.

You can test this with the following patient journey. It should fail most of the time and redirect you to the error view.

"I am very sick. I need help. I have Covid-19. I am in the hospital. I am in the ICU. I am on a ventilator. Please send help quickly."

### CODE REVIEW

**Comment by thangixd** [comment]
Wow that was fast! Great job!!!

**Comment by tkv29** [comment]
GJ ! PO Testing✅

I noticed you use width 97% instead of 100%, you need to add box-sizing: border-box so it considers the border as the border
image

**Comment by PitButtchereit** [comment]
FYI: Database is pushed because I resolved merge conflicts from #91

**Review by thangixd — APPROVED** [review]

**Review by nils-schmitt — APPROVED** [review]
Very good job, looks good and gives a much more valuable feeling

**Pull request merged**
